### ISSUE TITLE
sort_topo bug

### ISSUE THREAD

**Issue by ckampfe** [ckampfe/strand#1]
```
iex(5)> Alg.sort_topo(%{a: [], b: [:a], c: [:b]})                                                                                                    ** (FunctionClauseError) no function clause matching in MapSet.member?/2                                                                                 (elixir) lib/map_set.ex:249: MapSet.member?([], :a)
    (elixir) lib/enum.ex:818: anonymous fn/3 in Enum.filter/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1772: Enum.filter/2
    (strand) lib/strand/alg.ex:32: Strand.Alg.do_kahn/3
```
vs
```
iex(5)> Alg.sort_topo(%{a: MapSet.new([]), b: MapSet.new([:a]), c: MapSet.new([:b])})
[:a, :b, :c]
```

**Comment by ckampfe** [comment]
fixed in 0.3.2
